import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
const publicBaseUrl = packageJson.mapCanvas?.publicBaseUrl;
if (typeof publicBaseUrl !== "string" || !URL.canParse(publicBaseUrl)) {
  throw new Error("package.json mapCanvas.publicBaseUrl must be an absolute URL");
}

const result = await build({
  entryPoints: [path.join(root, "widget/src.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  loader: { ".png": "dataurl" },
  minify: true,
  write: false,
  outdir: "out",
});

const js = result.outputFiles.find((file) => file.path.endsWith(".js"));
const css = result.outputFiles.find((file) => file.path.endsWith(".css"));
if (!js || !css) throw new Error("Expected esbuild to emit JavaScript and CSS");

const template = await readFile(path.join(root, "widget/index.html"), "utf8");
const scriptTag = '<script type="module" src="./src.ts"></script>';
const bodyStart = template.indexOf("<body>");
const scriptStart = template.indexOf(scriptTag);
if (bodyStart < 0 || scriptStart < 0 || scriptStart <= bodyStart) {
  throw new Error("Widget template does not contain the expected body and module script");
}

const bodyMarkup = template.slice(bodyStart + "<body>".length, scriptStart).trim();
const runtimePrelude = [
  `const mapCanvasStyle=document.createElement("style");`,
  `mapCanvasStyle.dataset.mapCanvas="runtime";`,
  `mapCanvasStyle.textContent=${JSON.stringify(css.text)};`,
  `document.head.append(mapCanvasStyle);`,
  `document.body.innerHTML=${JSON.stringify(bodyMarkup)};`,
].join("");
const assetSource = `${runtimePrelude}\n${js.text}\n`;
const assetVersion = createHash("sha256").update(assetSource).digest("hex").slice(0, 16);
const versionedAssetPath = `/assets/v/${assetVersion}/map-widget.js`;
const fallbackAssetPath = "/assets/current/map-widget.js";
const versionedAssetUrl = new URL(versionedAssetPath, publicBaseUrl).href;
const fallbackAssetUrl = new URL(fallbackAssetPath, publicBaseUrl).href;

const loaderTemplate = await readFile(path.join(root, "widget/loader.html"), "utf8");
const loaderHtml = loaderTemplate.replaceAll("__MAP_CANVAS_ASSET_ORIGIN__", publicBaseUrl);
if (loaderHtml === loaderTemplate) {
  throw new Error("Widget loader is missing the asset-origin placeholder");
}

const dist = path.join(root, "dist");
const publicDirectory = path.join(dist, "public");
await rm(dist, { recursive: true, force: true });
await mkdir(path.join(publicDirectory, "assets/v", assetVersion), { recursive: true });
await mkdir(path.join(publicDirectory, "assets/current"), { recursive: true });
await writeFile(path.join(dist, "map-widget.html"), loaderHtml, "utf8");
await writeFile(path.join(publicDirectory, versionedAssetPath.slice(1)), assetSource, "utf8");
await writeFile(path.join(publicDirectory, fallbackAssetPath.slice(1)), assetSource, "utf8");
await writeFile(
  path.join(publicDirectory, "_headers"),
  [
    "/assets/v/*",
    "  Access-Control-Allow-Origin: *",
    "  Cache-Control: public, max-age=31536000, immutable",
    "",
    "/assets/current/*",
    "  Access-Control-Allow-Origin: *",
    "  Cache-Control: public, no-cache, must-revalidate",
    "",
  ].join("\n"),
  "utf8",
);
await writeFile(
  path.join(root, "src/generated-widget-build.ts"),
  [
    "// Generated by scripts/build-widget.mjs. Do not edit.",
    `export const WIDGET_ASSET_ORIGIN = ${JSON.stringify(new URL(publicBaseUrl).origin)};`,
    `export const WIDGET_ASSET_VERSION = ${JSON.stringify(assetVersion)};`,
    `export const WIDGET_ASSET_URL = ${JSON.stringify(versionedAssetUrl)};`,
    `export const WIDGET_FALLBACK_ASSET_URL = ${JSON.stringify(fallbackAssetUrl)};`,
    "",
  ].join("\n"),
  "utf8",
);
